title: pierre deroudilhe
author: pierre deroudilhe
email: pierre.deroudilhe@pm.me
url: https://deroudilhep.github.io
baseurl: 
description: > 
  Sur ce site, vous pouvez retrouver une liste des articles que j'ai publié dans le cadre de mon activité de journaliste, de mes études, ainsi que certains projets au plus long terme. Les liens ci-dessous vous permettent d'accéder facilement à une période, une activité ou un projet en particulier. 

permalink: 

favicon: "favicon.png" # must be in the root directory

remote_theme: riggraz/no-style-please # special syntax for GitHub Pages 

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: "home" # customize text for homepage link in post layout
  date_format: "%d-%m-%Y" # customize how date is formatted
  show_description: true # show blog description in home page. can be true or false

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
