title: Pierre Deroudilhe
author: Pierre Deroudilhe
email: pierre.deroudilhe@protonmail.com
url: https://deroudilhep.github.io
baseurl: 
description: > 
  Sur ce site, vous retrouverez une liste choisie des papiers que j'ai publiés dans le cadre de mon activité de journaliste, ainsi que certains projets au plus long terme. Les liens ci-dessous vous permettent d'accéder facilement à une période, une activité ou un projet en particulier. 

permalink: 

favicon: "favicon.png" # must be in the root directory

remote_theme: riggraz/no-style-please # special syntax for GitHub Pages 

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: "home" # customize text for homepage link in post layout
  date_format: "%d-%m-%Y" # customize how date is formatted
  show_description: true # show blog description in home page. can be true or false

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
