title: Pierre Deroudilhe
author: Pierre Deroudilhe
email: pierre.deroudilhe@protonmail.com
url: https://deroudilhep.github.io
baseurl: 
description: > 
  Journaliste, je termine mon cursus en datajournalisme et enquête au Centre de formation des journalistes à Paris et suis alternant au sein du service Data-Sup Recherche d'AEF Info. 

permalink: 

favicon: "favicon.png" # must be in the root directory

remote_theme: riggraz/no-style-please # special syntax for GitHub Pages 

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%d-%m-%Y" # customize how date is formatted
  show_description: true # show blog description in home page. can be true or false

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
