project:
  type: website
  output-dir: docs

website:
  title: Pierre Deroudilhe
  description: |
    Site web et blog de Pierre Deroudilhe, journaliste et datajournaliste à AEF info.
  favicon: favicon.png
  site-url: https://deroudilhep.github.io
  page-navigation: true
  twitter-card: true
  open-graph:
    locale: fr_FR
    
  navbar:
    search: true
    
    right:
      - icon: twitter
        href: https://twitter.com/deroudilhep
      - icon: mastodon
        href: https://fosstodon.org/@deroudilhep
      - icon: github
        href: https://github.com/deroudilhep
      - icon: linkedin
        href: https://www.linkedin.com/in/pierre-deroudilhe
      - icon: rss
        href: posts_index.xml
        
    left:
      - text: Posts de blog
        href: posts_index.qmd
      - text: CV
        href: cv.qmd
  
  page-footer:
    center:
      - text: Posts de blog
        href: posts_index.qmd
      - text: CV
        href: cv.qmd

format:
  html:
    lang: fr
    toc: true
    toc-title: Sur cette page
    toc-depth: 4
    css: styles.css
    theme: 
      - united
      - custom.scss
    anchor-sections: true
    link-external-icon: true
    link-external-newwindow: true
    code-copy: true
    code-overflow: wrap
    tbl-cap-location: bottom