project:
  type: website

website:
  title: "Pierre Deroudilhe"
  site-url: "https://deroudilhep.github.io"
  navbar:
    search: true
    tools:
      - icon: twitter
        href: https://twitter.com/deroudilhep
      - icon: mastodon
        href: https://fosstodon.org/@deroudilhep
      - icon: github
        href: https://github.com/deroudilhep
    left:
      - text: Posts de blog
        href: posts_index.qmd
      - text: CV
        href: cv.pdf
  page-navigation: true
  page-footer:
    center:
      - text: À propos
        href: about.qmd
      - text: CV
        href: cv.pdf
    right:
      - icon: twitter
        href: https://twitter.com/deroudilhep
      - icon: mastodon
        href: https://fosstodon.org/@deroudilhep
      - icon: github
        href: https://github.com/deroudilhep
    border: false

format:
  html:
    theme: pulse
    css: styles.css



