project:
  type: website

website:
  title: "Pierre Deroudilhe"
  site-url: "https://deroudilhep.github.io"
  description: "Le site web de Pierre Deroudilhe, journaliste et datajournaliste à AEF info."
  favicon: favicon.jpg
  twitter-card: true
  open-graph:
    locale: fr_FR
  navbar:
    right:
      - icon: twitter
        href: https://twitter.com/deroudilhep
      - icon: mastodon
        href: https://fosstodon.org/@deroudilhep
      - icon: github
        href: https://github.com/deroudilhep
      - icon: rss
        href: posts_index.xml
    left:
      - text: Posts de blog
        href: posts_index.qmd
      - text: CV
        href: docs/cv.qmd
  page-navigation: true
  page-footer:
    center:
      - text: Posts de blog
        href: posts_index.qmd
      - text: CV
        href: cv.pdf
    right:
      - icon: twitter
        href: https://twitter.com/deroudilhep
      - icon: mastodon
        href: https://fosstodon.org/@deroudilhep
      - icon: github
        href: https://github.com/deroudilhep
      - icon: rss
        href: posts_index.xml

format:
  html:
    toc: true
    toc-title: Sur cette page
    link-external-icon: true
    link-external-newwindow: true
    code-overflow: wrap
    code-copy: true
    theme:
      - united
      - custom.scss
    css: styles.css



