project:
  type: website

website:
  title: "Pierre Deroudilhe"
  site-url: "https://deroudilhep.github.io"
  description: "Le site web de Pierre Deroudilhe, journaliste et datajournaliste à AEF info."
  favicon: favicon.jpg
  twitter-card: true
  open-graph:
    locale: fr_FR
  navbar:
    search: true
    right:
      - icon: twitter
        href: https://twitter.com/deroudilhep
      - icon: mastodon
        href: https://fosstodon.org/@deroudilhep
      - icon: github
        href: https://github.com/deroudilhep
      - icon: rss
        href: posts_index.xml
    left:
      - text: Posts de blog
        href: posts_index.qmd
      - text: CV
        href: cv.pdf
  page-navigation: true
  page-footer:
    center:
      - text: À propos
        href: about.qmd
      - text: CV
        href: cv.pdf
    right:
      - icon: twitter
        href: https://twitter.com/deroudilhep
      - icon: mastodon
        href: https://fosstodon.org/@deroudilhep
      - icon: github
        href: https://github.com/deroudilhep
    border: false

format:
  html:
    theme: pulse
    css: styles.css



