project:
  type: website
  output-dir: docs

website:
  title: Pierre Deroudilhe
  description: >
    Site web de Pierre Deroudilhe, journaliste et datajournaliste à AEF info.
    Compétences, expériences et formation, articles, code et documentation.
  image: profil.jpg
  favicon: favicon.png
  twitter-card:
    creator: "@deroudilhep"
  open-graph:
    locale: fr_FR
    site-name: pderoudilhe.fr
  site-url: https://pderoudilhe.fr

  navbar:
    search: true

    left:
      - text: Articles
        href: posts_index.qmd
      - text: CV
        href: cv.qmd
      - text: Contact
        href: contact.qmd

    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/pierre-deroudilhe
      - icon: github
        href: https://github.com/deroudilhep
      - icon: mastodon
        href: https://fosstodon.org/@deroudilhep
      - icon: twitter
        href: https://twitter.com/deroudilhep
      - icon: rss
        href: posts_index.xml

  page-footer:
    left: "Copyright 2025, Pierre Deroudilhe"

    center:
      - text: Articles
        href: posts_index.qmd
      - text: CV
        href: cv.qmd
      - text: Contact
        href: contact.qmd

    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/pierre-deroudilhe
      - icon: github
        href: https://github.com/deroudilhep
      - icon: mastodon
        href: https://fosstodon.org/@deroudilhep
      - icon: twitter
        href: https://twitter.com/deroudilhep
      - icon: rss
        href: posts_index.xml

format:
  html:
    lang: fr
    tbl-cap-location: bottom
    toc: true
    toc-title: Sur cette page
    css: styles.css
    anchor-sections: true
    link-external-newwindow: true
    code-overflow: wrap
    code-copy: true
    theme:
      - spacelab
      - custom.scss
