---
title: Pierre Deroudilhe
subtitle: Journaliste, datajournaliste
format:
  html:
    toc: false
    link-external-icon: false
    grid: 
      margin-width: 400px
---

:::{.column-margin}
| | |
|---|---|
| Mail perso | <pierre.deroudilhe@pm.me> |
| Résidence | Paris |
| Âge | 25 ans |
| CIJP | n° 137393 |
| Permis | B |
:::

### Compétences

#### Data

Statistiques et probabilités\
Tableur et R\
Datawrapper, Flourish, Tableau, etc.

#### Enquête

Méthodes de l'enquête (dont écriture)\
*OSINT*\

#### Code et programmation

R (automatisation, scraping...)\
HTML et CSS\
*Shell scripting*, *Command Line*, systèmes Linux

#### Langues

Anglais niveau C1 (Cambridge Advanced: 188/230)

### Expériences professionnelles

**Journaliste**\
*AEF info, Paris* | Depuis octobre 2021\
Fil Data-Sup Recherche, puis pour les cinq pôles de la rédaction : enquêtes, analyse et mise en forme de données, rédaction et publication de dépêches, création de solutions techniques pour le traitement de la donnée au sein de la rédaction, formation à destination des confrères et consoeurs

**Journaliste (stage)**\
*Le Parisien, Paris* | De juillet à août 2021\
Service Data et innovation, analyse de données, lien avec le service  Infographie, rédaction d'articles et assistance aux autres services du Web pour le traitement de la donnée

### Diplômes et formation

**Datajournalisme et enquête**\
*CFJ, Paris* | De 2020 à 2022\
Double diplôme avec Sciences Po Lyon (grade master)

**L'Académie**\
*ESJ, Lille* | De 2018 à 2020\
Préparation aux concours des écoles de journalisme

**Licence d'Histoire**\
*Université Lille III* | De 2018 à 2019

**Classe préparatoire littéraire**\
*Lycée Édouard Herriot, Lyon* | De 2016 à 2018\
Khâgne Chartes option géographie
